name: flutter_base_project
description: Base for Flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # for state management
  flutter_riverpod: any
  # for http client
  http: any
  # for local data
  shared_preferences: any
  # for json model
  json_annotation: any
  freezed: any
  # for image network
  cached_network_image: any
  # for permission requests
  permission_handler: any
  # google fonts
  google_fonts: any
  # icons svg
  flutter_svg: any
  # other
  url_launcher: any
  collection: any
  intl: any
  equatable: any
  gap: any

  # for firebase
  #  firebase_core: any
  #  cloud_firestore: any
  #  firebase_messaging: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  json_serializable: any

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
